from _typeshed import Incomplete

stop_event: Incomplete

class MyModel:
    output_class: Incomplete
    batch_size: Incomplete
    learningrate: Incomplete
    writer: Incomplete
    training_device: str
    iterate_time: int
    data_split_rate: float
    train_size: int
    val_size: int
    input_image: Incomplete
    output_result: Incomplete
    def __init__(self, output_class, batch_size: int = 100, lr: float = 0.01, inference_model: Incomplete | None = None) -> None: ...
    model: Incomplete
    def load_model(self) -> None: ...
    def model_freeze(self) -> None: ...
    def load_single_img(self, image_path): ...
    def load_single_img_cv2(self, image_path): ...
    train_loader: Incomplete
    val_loader: Incomplete
    def load_dataset(self, root_dir_train) -> None: ...
    def load_testdata(self, root_dir_test) -> None: ...
    loss_fn: Incomplete
    optimizer: Incomplete
    scheduler: Incomplete
    def init_loss_optimizer(self) -> None: ...
    def train(self, dataloader, model, loss_fn, optimizer): ...
    def validation(self, dataloader, model, loss_fn): ...
    def inference_test(self, dataloader, model, loss_fn): ...
    def save_model(self, model_name) -> None: ...
    acc_pre: int
    def start_train(self, train_dataset, epoch, model_name) -> None: ...
    def start_inference(self, model_path, test_Dataset) -> None: ...
    def load_inference_model(self, model_path) -> None: ...
    def start_inference_single(self, test_image): ...
    def start_inference_single_withcallback(self, test_image, callback): ...
    def start_inference_single_withcallback_image(self, callback) -> None: ...
    inference_threading: Incomplete
    def start_inference_single_thread(self, callback) -> None: ...
    def push_image(self, image) -> None: ...
    def get_image_result(self): ...
    def is_result_empty(self): ...
    def close_inference(self) -> None: ...
